### ISSUE TITLE
Revert changes on additional configurations on tide

### ISSUE THREAD

**Issue by Jeffwan** [kitex-contrib/test-infra#29]
Since we already figure out the `merge type not allowed` issue,  we know that below PRs are helpless. Let's revert the change and make the configuration clean. 

- https://github.com/kitex-contrib/test-infra/pull/23
- https://github.com/kitex-contrib/test-infra/pull/25 (partial - only secret part)

**Comment by Summer-Field** [comment]
OK I will  revert the change now.

**Comment by Summer-Field** [comment]
Commit new PR to make the configuration clean.
Close this issue.
